name: Discord Webhooks

on:
    issues:
        types: [closed, deleted, edited, opened]
    push:

jobs:
    discord-webhooks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Execute Discord Webhooks
              uses: FancyStudioTeam/GitHub-Actions@main
              with:
                  webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
                  webhook_thread_id: ${{ secrets.DISCORD_WEBHOOK_THREAD_ID }}
                  webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
